import { NextResponse } from "next/server";
import { createOpenAI } from "@ai-sdk/openai";
import { streamText, ModelMessage } from "ai";

export async function POST(request: Request) {
  let llmProvider = "llamacpp";
  try {
    const body = await request.json();
    const { messages, settings } = body;

    if (!messages || !Array.isArray(messages)) {
      return NextResponse.json(
        { error: "Conversation messages list is required" },
        { status: 400 }
      );
    }

    const currentSettings = settings || {
      type: "t2i",
      model: "flux-dev",
      steps: 25,
      guidance: 6.0,
      width: 1024,
      height: 1024,
      llmProvider: "llamacpp",
    };

    llmProvider = currentSettings.llmProvider || "llamacpp";
    const apiKey = process.env.OPENROUTER_API_KEY;
    const modelName = process.env.OPENROUTER_MODEL || "google/gemini-2.5-flash";

    let clientProvider;
    let targetModel;

    // Set up the LLM provider client
    if (llmProvider === "llamacpp") {
      const baseURL = process.env.LLAMACPP_API_URL || "http://127.0.0.1:8080/v1";
      targetModel = process.env.LLAMACPP_MODEL_NAME || "local-model";
      
      clientProvider = createOpenAI({
        baseURL: baseURL,
        apiKey: "no-key-required",
      });
    } else {
      // Fallback if OpenRouter is chosen but key is unconfigured
      if (!apiKey || apiKey === "your_openrouter_api_key_here" || apiKey.trim() === "") {
        return new Response("⚠️ **API Key Missing:** Please add your `OPENROUTER_API_KEY` to the `.env.local` file to start chatting, or switch to **Llama.cpp (Local)** in Generator Settings.", { status: 400 });
      }

      targetModel = modelName;
      clientProvider = createOpenAI({
        baseURL: "https://openrouter.ai/api/v1",
        apiKey: apiKey,
        headers: {
          "HTTP-Referer": "https://krumstudio.com",
          "X-Title": "Krum Studio",
        },
      });
    }

    const generationMode = currentSettings.type || "t2i";

    // Build mode-specific guidance block
    let modeGuidance = "";
    if (generationMode === "t2i") {
      modeGuidance = `## Active Mode: Text-to-Image (Flux.2 Dev)
The user wants a STILL IMAGE generated by Flux.2 Dev — a state-of-the-art image model built on Mistral-3-Small text understanding.

**Prompting style for Flux.2:**
- Lead with subject + aesthetic: "A 35mm analog portrait of a Moroccan woman..."
- Add material/texture detail: fabric, skin, architecture surfaces
- Include lighting setup: "shot under diffused studio softbox", "golden hour backlight", "cinematic ARRI"
- Mention post-processing feel: "film grain", "HDR color grading", "crisp 8K detail"
- Flux.2 responds well to photography, fashion, and hyper-realism prompts

**Trigger JSON for t2i:**
[TRIGGER_GENERATION]
{
  "enhancedPrompt": "...",
  "steps": 20,
  "guidance": 4.0,
  "width": 1024,
  "height": 1024
}`;
    } else if (generationMode === "i2i") {
      modeGuidance = `## Active Mode: Image Edit (Qwen-Image 2511)
The user wants an EXISTING IMAGE EDITED by Qwen-Image 2511 — an instruction-following edit model. It takes the user's uploaded reference image and applies the requested change.

**Prompting style for Qwen-Image edits:**
- Describe WHAT TO CHANGE, not what the full scene looks like
- Be specific: "Add dragon wings to the person's back, keep the background unchanged"
- Instruction-style works best: "Replace the sky with a starry night", "Make the car chrome colored"
- Avoid full-scene descriptions — the model already sees the input image
- If the user hasn't uploaded an image yet, ASK them to upload one before triggering generation

**Trigger JSON for i2i:**
[TRIGGER_GENERATION]
{
  "enhancedPrompt": "...",
  "steps": 40,
  "guidance": 4.0,
  "width": 1024,
  "height": 1024
}`;
    } else if (generationMode === "t2v" || generationMode === "i2v") {
      const isI2V = generationMode === "i2v";
      modeGuidance = `## Active Mode: ${isI2V ? "Image-to-Video" : "Text-to-Video"} (LTX-2.3)
The user wants a VIDEO generated by LTX-2.3 — a 22B parameter cinematic video model with a built-in **Gemma-3-12B AI prompt enhancer**. The user's prompt is automatically refined by Gemma before reaching the video model, so write a solid director-style foundation and Gemma will expand it cinematically.
${isI2V ? "\n**IMPORTANT:** i2v mode requires a reference image. If the user hasn't uploaded one, ask them to upload their starting frame before you trigger generation.\n" : ""}
**LTX-2.3 Director Method — prompt structure:**
1. **Subject:** Who/what is the main subject? (e.g., "A woman in her 30s with auburn hair")
2. **Action:** Specific verbs, not adjectives. (e.g., "slowly stirs her coffee and gazes out the rain-streaked window" NOT "dynamic movement")
3. **Environment & Lighting:** Texture, surfaces, light source. (e.g., "warm tungsten interior, rain bokeh on glass, wooden bistro table")
4. **Camera Intent:** Explicit camera behavior. (e.g., "slow push-in", "side tracking shot at eye level", "handheld feel with subtle breathing")
5. **Audio/Atmosphere (optional):** Rain, ambient noise, music style — LTX-2.3 supports audio

**Do NOT:**
- Cram multiple scenes into one prompt — focus on ONE continuous shot
- Use vague words like "dynamic", "stunning", "epic" without specifics
- Skip the camera move — it's critical for video coherence

**Tip:** Keep the prompt focused. Gemma will add cinematic language automatically.

**Trigger JSON for ${isI2V ? "i2v" : "t2v"}:**
[TRIGGER_GENERATION]
{
  "enhancedPrompt": "...",
  "steps": 25,
  "guidance": 3.5,
  "width": 1280,
  "height": 720,
  "duration": 121,
  "fps": 25
}
(duration = frame count: 121 ≈ 5s, 193 ≈ 8s, 257 ≈ 10s at 25fps)`;
    }

    const systemPrompt = `You are a premium AI Creative Director for Krum Studio. Your role is to guide the user in crafting a stunning ${generationMode.includes("v") ? "video" : "image"} generation prompt, then trigger the generation at the right moment.

${modeGuidance}

## Conversation Rules
1. **Ask first, generate second.** Gather key creative details (subject, mood, lighting, composition) through conversation.
2. **Offer concrete suggestions** when the user is vague — give 2-3 specific style options to choose from.
3. **Trigger generation when:**
   - You have enough detail to write a complete, strong prompt
   - The user says "go ahead", "generate", "render", "surprise me", or similar
   - The user says "figure it out yourself"
4. **Never** output the [TRIGGER_GENERATION] block mid-conversation or before you have a clear concept.
5. **Keep responses concise** — this is a creative back-and-forth, not an essay.

## Trigger Format
When ready, append this EXACTLY at the end of your response (no other text after it):

[TRIGGER_GENERATION]
{ ... the appropriate JSON for the active mode above ... }`;

    const formattedMessages: ModelMessage[] = messages.map((m: any) => {
      if (m.role === "user") {
        return {
          role: "user" as const,
          content: String(m.content),
        };
      }
      return {
        role: "assistant" as const,
        content: String(m.content),
      };
    });

    console.log(`Routing Chat request to ${llmProvider} (${targetModel})`);

    const result = await streamText({
      model: clientProvider.chat(targetModel),
      system: systemPrompt,
      messages: formattedMessages,
    });

    return result.toTextStreamResponse();

  } catch (error: any) {
    console.error("Error in chat api route:", error);
    
    const errMsg = error.message || "";
    const isConnRefused = errMsg.includes("ECONNREFUSED") || errMsg.includes("fetch failed");

    let reply = "⚠️ **Error:** Failed to communicate with the selected LLM provider.";
    if (isConnRefused) {
      if (llmProvider === "llamacpp") {
        reply = `⚠️ **Llama.cpp Connection Refused:** Could not connect to your local model server at \`${process.env.LLAMACPP_API_URL || "http://127.0.0.1:8080/v1"}\`. Please verify your Llama.cpp server is running and its API URL is configured correctly.`;
      } else {
        reply = "⚠️ **Connection Refused:** Could not connect to the OpenRouter API. Please check your internet connection.";
      }
    } else {
      reply = `⚠️ **LLM Error:** ${error.message || "An unexpected error occurred during reasoning."}`;
    }

    return new Response(reply, { status: 500 });
  }
}
